name: habit_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^6.0.0
  uni_links: ^0.5.1
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_slidable: ^3.0.0
  flutter_app_badger: ^1.5.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  flutter_apns_only: ^1.5.2
  push: ^2.2.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.0
  fl_chart: ^0.68.0
  flutter_native_splash: ^2.4.7
  google_generative_ai: ^0.4.3
  dash_chat_2: ^0.0.19
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/app_logo.png
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
